# Generated by Django 4.2.1 on 2023-05-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_capture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='monto_compra',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='fecha',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='concepto_pago',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exitoso',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='franquicia',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='medio_pago',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='numero_cuotas',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='numero_transaccion',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sede',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
