# Generated by Django 4.2.1 on 2023-05-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_validation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='numero_tarjeta',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='tipo_tarjeta',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='usuario',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
