# Generated by Django 4.2.1 on 2023-05-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='activo',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='nombre_medio_pago',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='usuario',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
